name: paiqi_app
description: 排期天菜——专为中国音乐剧观众打造的排期管理App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  table_calendar: ^3.0.9
  intl: ^0.20.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  crypto: ^3.0.3
  lunar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/stardrop.png
    - assets/profile_avatar.png
    - assets/user_data.json
